import '@/assets/globals.css'
import { DM_Sans } from 'next/font/google'
import Navbar from "@/components/navbar";

const dmSans = DM_Sans({
  weight: '400',
  subsets: ['latin'],
})

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="it">
      <body className={dmSans.className}>
        <main className="max-w-4xl mx-auto">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
